layout_spectrum: 0.9631104697473347
typography_spectrum: 0.6595116192474961
color:
  brandStrength: 0.8379898581188172
  lightness: 0.00009862380102276802
  saturation: 0.8812418659217656
  rhythmicContrast: 0.7724519888870418
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
name: ShoreDan Projects
